// <auto-generated />
namespace Thinktecture.IdentityServer.Core.Repositories.Migrations.SqlCe
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class PrimaryPassiveEndpoint : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PrimaryPassiveEndpoint));
        
        string IMigrationMetadata.Id
        {
            get { return "201312131157039_PrimaryPassiveEndpoint"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
