//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thinktecture.IdentityServer.Resources.Models.Configuration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdfsIntegrationConfiguration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdfsIntegrationConfiguration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Thinktecture.IdentityServer.Resources.Models.Configuration.AdfsIntegrationConfigu" +
                            "ration", typeof(AdfsIntegrationConfiguration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifetime of the token.
        /// </summary>
        public static string AuthenticationTokenLifetime {
            get {
                return ResourceManager.GetString("AuthenticationTokenLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the lifetime of the token (in minutes).
        /// </summary>
        public static string AuthenticationTokenLifetimeDescription {
            get {
                return ResourceManager.GetString("AuthenticationTokenLifetimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthenticationTokenLifetime cannot be negative.
        /// </summary>
        public static string AuthenticationTokenLifetimeRangeErrorMessage {
            get {
                return ResourceManager.GetString("AuthenticationTokenLifetimeRangeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADFS Encryption certificate.
        /// </summary>
        public static string EncryptionCertificate {
            get {
                return ResourceManager.GetString("EncryptionCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADFS Encryption certificate.
        /// </summary>
        public static string EncryptionCertificateDescription {
            get {
                return ResourceManager.GetString("EncryptionCertificateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADFS Federation Endpoint.
        /// </summary>
        public static string FederationEndpoint {
            get {
                return ResourceManager.GetString("FederationEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address of the ADFS federation endpoint (mixed/symmetric/basic256)..
        /// </summary>
        public static string FederationEndpointDescription {
            get {
                return ResourceManager.GetString("FederationEndpointDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADFS Signing Certificate Thumbprint.
        /// </summary>
        public static string IssuerThumbprint {
            get {
                return ResourceManager.GetString("IssuerThumbprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbprint of the ADFS signing certificate..
        /// </summary>
        public static string IssuerThumbprintDescription {
            get {
                return ResourceManager.GetString("IssuerThumbprintDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADFS Issuer URI.
        /// </summary>
        public static string IssuerUri {
            get {
                return ResourceManager.GetString("IssuerUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADFS Issuer URI.
        /// </summary>
        public static string IssuerUriDescription {
            get {
                return ResourceManager.GetString("IssuerUriDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable JWT authentication.
        /// </summary>
        public static string JwtAuthenticationEnabled {
            get {
                return ResourceManager.GetString("JwtAuthenticationEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables the OAuth2 to ADFS authentication bridge.
        /// </summary>
        public static string JwtAuthenticationEnabledDescription {
            get {
                return ResourceManager.GetString("JwtAuthenticationEnabledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FederationEndpoint required when JwtAuthenticationEnabled is enabled..
        /// </summary>
        public static string JwtAuthenticationEnabledRequiresFederationEndpointErrorMessage {
            get {
                return ResourceManager.GetString("JwtAuthenticationEnabledRequiresFederationEndpointErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IssuerUri required when JwtAuthenticationEnabled is enabled..
        /// </summary>
        public static string JwtAuthenticationEnabledRequiresIssuerUriErrorMessage {
            get {
                return ResourceManager.GetString("JwtAuthenticationEnabledRequiresIssuerUriErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass-through authentication token.
        /// </summary>
        public static string PassThruAuthenticationToken {
            get {
                return ResourceManager.GetString("PassThruAuthenticationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled, the original SAML token from ADFS will be passed back, otherwise the token will be converted to a JWT..
        /// </summary>
        public static string PassThruAuthenticationTokenDescription {
            get {
                return ResourceManager.GetString("PassThruAuthenticationTokenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IssuerThumbprint required when PassThruAuthenticationToken is false..
        /// </summary>
        public static string PassThruAuthenticationTokenRequiresIssuerThumbprintErrorMessage {
            get {
                return ResourceManager.GetString("PassThruAuthenticationTokenRequiresIssuerThumbprintErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable SAML authentication.
        /// </summary>
        public static string SamlAuthenticationEnabled {
            get {
                return ResourceManager.GetString("SamlAuthenticationEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables the OAuth2 to ADFS authentication bridge.
        /// </summary>
        public static string SamlAuthenticationEnabledDescription {
            get {
                return ResourceManager.GetString("SamlAuthenticationEnabledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FederationEndpoint required when SamlAuthenticationEnabled is enabled..
        /// </summary>
        public static string SamlAuthenticationEnabledRequiresFederationEndpointErrorMessage {
            get {
                return ResourceManager.GetString("SamlAuthenticationEnabledRequiresFederationEndpointErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IssuerThumbprint required when SamlAuthenticationEnabled is enabled..
        /// </summary>
        public static string SamlAuthenticationEnabledRequiresIssuerThumbprintErrorMessage {
            get {
                return ResourceManager.GetString("SamlAuthenticationEnabledRequiresIssuerThumbprintErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IssuerUri required when SamlAuthenticationEnabled is enabled..
        /// </summary>
        public static string SamlAuthenticationEnabledRequiresIssuerUriErrorMessage {
            get {
                return ResourceManager.GetString("SamlAuthenticationEnabledRequiresIssuerUriErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable username/password authentication.
        /// </summary>
        public static string UsernameAuthenticationEnabled {
            get {
                return ResourceManager.GetString("UsernameAuthenticationEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables the OAuth2 to ADFS authentication bridge.
        /// </summary>
        public static string UsernameAuthenticationEnabledDescription {
            get {
                return ResourceManager.GetString("UsernameAuthenticationEnabledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserNameAuthenticationEndpoint required when UsernameAuthenticationEnabled is enabled..
        /// </summary>
        public static string UserNameAuthenticationEnabledRequiresUserNameAuthenticationEndpointErrorMessage {
            get {
                return ResourceManager.GetString("UserNameAuthenticationEnabledRequiresUserNameAuthenticationEndpointErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADFS UserName Endpoint.
        /// </summary>
        public static string UserNameAuthenticationEndpoint {
            get {
                return ResourceManager.GetString("UserNameAuthenticationEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address of the ADFS UserNameMixed endpoint..
        /// </summary>
        public static string UserNameAuthenticationEndpointDescription {
            get {
                return ResourceManager.GetString("UserNameAuthenticationEndpointDescription", resourceCulture);
            }
        }
    }
}
